#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Sample.Resource", IsApplication=true)]

namespace Sample
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040002
			public const int colorAccent = 2130968578;
			
			// aapt resource value: 0x7f040000
			public const int colorPrimary = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int colorPrimaryDark = 2130968577;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f050000
			public const int activity_horizontal_margin = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int activity_vertical_margin = 2131034113;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080000
			public const int activity_main = 2131230720;
			
			// aapt resource value: 0x7f08000b
			public const int btn_hide_popup = 2131230731;
			
			// aapt resource value: 0x7f08000d
			public const int btn_s_b_d = 2131230733;
			
			// aapt resource value: 0x7f08000c
			public const int btn_s_b_l = 2131230732;
			
			// aapt resource value: 0x7f08000a
			public const int btn_show_popup = 2131230730;
			
			// aapt resource value: 0x7f080005
			public const int file = 2131230725;
			
			// aapt resource value: 0x7f080006
			public const int file_card_style = 2131230726;
			
			// aapt resource value: 0x7f080001
			public const int how_to_use = 2131230721;
			
			// aapt resource value: 0x7f080007
			public const int image = 2131230727;
			
			// aapt resource value: 0x7f080008
			public const int image_show_specific = 2131230728;
			
			// aapt resource value: 0x7f080004
			public const int link = 2131230724;
			
			// aapt resource value: 0x7f080009
			public const int multi_images = 2131230729;
			
			// aapt resource value: 0x7f080002
			public const int text = 2131230722;
			
			// aapt resource value: 0x7f080003
			public const int text_card_style = 2131230723;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int activity_main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f020000
			public const int avatar = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int drag_card_bg = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int drag_card_content = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_fso_folder = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_launcher = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int music_cover = 2130837509;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060000
			public const int app_name = 2131099648;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int AppTheme = 2131165184;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
